#
# default: &default
#   adapter: postgresql
#   encoding: unicode
#   pool: 5
#   template: template0
#
# development:
#   <<: *default
#   database: archieve_development
#
# test:
#   <<: *default
#   database: archieve_test
#
# production:
#   <<: *default
#   database: archieve_production
#   username: archieve
#   password: <%= ENV['ARCHIEVE_DATABASE_PASSWORD'] %>

default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  template: template0

development:
  <<: *default
  database: achieve_development

test:
  <<: *default
  database: achieve_test

production:
  <<: *default
  database: achieve_production
  username: achieve
  password: <%= ENV['ACHIEVE_DATABASE_PASSWORD'] %>
